language: cpp

compiler:
  - gcc

os:
  - linux
  - osx

env:
  matrix:
  - NODE_VERSION="0.10.33" ATOM_VERSION="0.21.1"
  global:
  - secure: "EXgVgtayyyxt7flmPhwKZIvkqfkpX1TnrX/EX7ZEQ36TuZGYYX5OXjLTtXWk9sSE6l6O3wRewpkou2PvQQpX25yOI8XYD8vBjx3ymt1lg5RS8nTDZO0XHsd0aTV7JxJCyZGCkIYXvVRPpVbLDbGwULhJe55p8YYKx/lohDB3FYM="
  - secure: "YvtR+B6yC+MxsU7tP6FCEHKLZoRfvlfwX5HSs8eAYWxqrZmIqJTbavSlj4bQ919szyQ1vZ8wTMkXd/8tCqWARTyWA8tLOHgXm/ZAlxdtdtotyZzNsbC0FmtJHF/wmaQcJ4lX2vcWWhOwtEetEULO6Hv0xGiW26aK+Jp240f6NJE="
  - secure: "FxiGeOfdx5gi6F9axPog/9ErQN7ekvSpWTLgkX5ELJGhYncl0jOyvpkJhQan/hqf6kk4SG8+JVB+R4YyN2pwh2CYZ0jNEuLvApFrIt9YRKcnMbeBkjDbAq8ZcOVm2Zjtl22N0qLWLbvUsf71AM1S9s7a8yJL/Ux62IJQxA6HDic="
#CRED
  - secure: "Q/ZZ4MYCjzppmERnEPCArm/3UU7pQ4hZ5O+Dq+cZG75nKS6Oc+HmD+chcJOGRqriLruJxfqxd7oB0G8UD4Z4F6Kc7mdBzIjcizkGMOGKBQjKfrB4G+0q3fEUhr+fyrDl+c9at3Qh6emiUdlvvSUhivNoJ/TsGqh8oD9IpCU9krg="
#EC2ACC
  - secure: "ZVWT6/GeTqmnUqhYjU9hXv9oqMw0gzbyuGCtNtVPB458bDvd52MymuW38J5i2nWS/1xIcH8fKs5nna1G2ImQ8H+4XXFPtAa6LG9hN3yIkoysuK+AN37gH4DPX/rOMaoUPRVCstvusQ8qYfJcTwCGZBs2NXJwE3e1OR7RfjzJuoU="
#EC2SEC
  - secure: "UN2QP+b6urxyk9o3M6ucfxVPSBwGeYBcDp/OJ1YUp9jvhn/FEaBve2u4EcTv8Zp+x4t3pVI70HYBwpOobQJN5b1PCz/t6bAthvAMQw2uZfFNu2gXMwPdARYpQFmrs/KvZPxyv6/qCux7Uu2PZBClghjpTCFE5hbT73mSnCm2WqU="
# http://about.travis-ci.org/blog/2013-11-29-postgresql-92-93-now-available/
# addons:
#   postgresql: "9.3"
# before_install:
#  - createdb template_postgis
#  - psql -c "CREATE EXTENSION postgis" template_postgis

before_install:
- git clone https://github.com/creationix/nvm.git ../.nvm && source ../.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- node --version
- npm --version
# install c++11 capable libstdc++ without sudo
- if [[ $(uname -s) == 'Linux' ]]; then wget https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test/+files/libstdc%2B%2B6_4.8.1-2ubuntu1~12.04_amd64.deb && dpkg -x libstdc++6_4.8.1-2ubuntu1~12.04_amd64.deb ./ && export LD_PRELOAD=$(pwd)/usr/lib/x86_64-linux-gnu/libstdc++.so.6; fi
# TODO: attempt to make build-travis sudoless
- ./scripts/build-travis.sh $TRAVIS_COMMIT
- ./scripts/windows-debug-server.sh

install:
- npm install --fallback-to-build=false
- python test/check_shared_libs.py node_modules/

before_script:
 - npm ls

script:
 - npm test
 - ./test/test-client.js
 - ./jekyll-test.sh

