language: cpp

compiler:
  - gcc

os:
  - linux
  - osx


env:
  matrix:
  - NODE_NVM_VERSION="0.10"
  global:
  - secure: "EXgVgtayyyxt7flmPhwKZIvkqfkpX1TnrX/EX7ZEQ36TuZGYYX5OXjLTtXWk9sSE6l6O3wRewpkou2PvQQpX25yOI8XYD8vBjx3ymt1lg5RS8nTDZO0XHsd0aTV7JxJCyZGCkIYXvVRPpVbLDbGwULhJe55p8YYKx/lohDB3FYM="
  - secure: "YvtR+B6yC+MxsU7tP6FCEHKLZoRfvlfwX5HSs8eAYWxqrZmIqJTbavSlj4bQ919szyQ1vZ8wTMkXd/8tCqWARTyWA8tLOHgXm/ZAlxdtdtotyZzNsbC0FmtJHF/wmaQcJ4lX2vcWWhOwtEetEULO6Hv0xGiW26aK+Jp240f6NJE="

# http://about.travis-ci.org/blog/2013-11-29-postgresql-92-93-now-available/
# addons:
#   postgresql: "9.3"
# before_install:
#  - createdb template_postgis
#  - psql -c "CREATE EXTENSION postgis" template_postgis

before_install:
- git clone https://github.com/creationix/nvm.git ../.nvm && source ../.nvm/nvm.sh
- nvm install $NODE_NVM_VERSION
- nvm use $NODE_NVM_VERSION
- node --version
- npm --version

install:
- npm install

before_script:
 - npm ls

script:
 - npm test
 - ./test/test-client.js

after_script:
- |
    PLATFORM=$(uname -s | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/")
    COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')
    GITSHA=$(echo "$COMMIT_MESSAGE" | grep -oE '\[publish [a-z0-9\-\.]+\]' | grep -oE '[a-z0-9\-\.]+' | tail -n1)
    if [ $PLATFORM == "linux" ] && [ -n "$GITSHA" ]; then
        echo "Publishing $GITSHA"
        sudo apt-get install -qy curl unzip nsis pip
        sudo pip install awscli
        ./scripts/build-atom.sh $GITSHA linux
        ./scripts/build-atom.sh $GITSHA darwin
        ./scripts/build-atom.sh $GITSHA win32
    fi

