language: node_js

node_js:
  - "0.10"

# http://about.travis-ci.org/blog/2013-11-29-postgresql-92-93-now-available/
addons:
  postgresql: "9.3"

before_install:
 - createdb template_postgis
 - psql -c "CREATE EXTENSION postgis" template_postgis
