source: docs
api: https://122e4e-mapbox.global.ssl.fastly.net
url: https://122e4e-mapbox.global.ssl.fastly.net
permalink: /:categories/:title
baseurl: /mapbox-studio
highlighter: true
mapboxjs: v2.0.0
tileapi: 'https://api.tiles.mapbox.com'
rdiscount:
  extensions: [smart]
